version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/tesing_sim_backend
hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  AllicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
  